--Trabalhar com números
integer
real
serial
numeric

--Trabalhar com textos
varchar
char
text

--Trabalhar com verdadeiro ou falso
boolean

--Trabalhar com data/hora
date
time
timestamp

--Criando a tabela Aluno
CREATE TABLE ALUNO (
	ID SERIAL,
	NOME VARCHAR(255),
	CPF CHAR(11),
	OBS TEXT,
	IDADE INTEGER,
	VALOR NUMERIC(10,2),
	ALTURA REAL,
	ATIVO BOOLEAN,
	DATA_NASCIMENTO DATE,
	HORA_AULA TIME,
	DT_MATRICULA TIMESTAMP
	
);
select * from aluno;

--INCLUINDO
INSERT INTO ALUNO (NOME,CPF,OBS,IDADE,VALOR,ALTURA,ATIVO,DATA_NASCIMENTO,HORA_AULA,DT_MATRICULA) 
VALUES ('DIOGO','132456484','JFOEIJVEOVHIEWPAHBESHEWOIAJFHEGOAHWG',37,100.50,1.82,TRUE,'1987-09-29','17:30:00','2022-01-05 15:06:02');

--ALTERANDO
UPDATE ALUNO
   SET NOME = 'ALVES',
       CPF = '1324564454',
	   OBS = 'JFOEIJVEOVHIFJEWIOVNEWV',
	   IDADE = 30,
	   VALOR = 102.56,
	   ALTURA = 1.75,
	   ATIVO = FALSE,
	   DATA_NASCIMENTO = '1990-10-05',
	   HORA_AULA = '14:30:01',
	   DT_MATRICULA = '2021-01-05 15:05:02'
 WHERE ID = 1;

 --EXCLUINDO
 DELETE FROM ALUNO WHERE ID = 1;